<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Thu, 23 Jul 2015 09:29:47 -0430
 */

$conf['title'] = 'Manual SIGAFS';
$conf['start'] = 'Inicio';
$conf['lang'] = 'es';
$conf['sidebar'] = 'rightSidebar';
$conf['license'] = 'publicdomain';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'root';
$conf['proxy']['pass'] = '<b>cm9vdA==';
$conf['plugin']['siteexport']['skipacl'] = 1;
$conf['plugin']['sidebar']['layout'] = 'outside';
$conf['tpl']['bootstrap3']['rightSidebar'] = 'rightSidebar';
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = '1';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cerulean';
$conf['tpl']['starterbootstrap']['sidebar_pos'] = 'Right';
$conf['tpl']['bassultemplar0203g6f43739']['sidebar_head'] = '1';
$conf['tpl']['bassultemplar0203g6f43739']['sidebar_foot'] = '1';
$conf['tpl']['dokubootstrapsimplified']['bootswatch'] = 'simplex';
$conf['htmlok'] = 1;
// end auto-generated content
